<?php /* Smarty version 2.6.14, created on 2011-01-16 15:28:26
         compiled from index_village_editor.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'urldecode', 'index_village_editor.tpl', 11, false),)), $this); ?>
<h2>Editeaza Sat)</h2>
<?php if ($this->_tpl_vars['result'] != ""): ?>
	<h4><?php echo $this->_tpl_vars['result']; ?>
</h4>
	<p>Nivelurile cladirilor au fost specificate.</p>
<?php endif; ?>
<h4>Schimba</h4>
<form action="index.php?screen=village_editor&amp;action=edit" method="POST">
Exista urmatoarele 
<select name="name">
<?php $_from = $this->_tpl_vars['v']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['village']):
?>
	<option value="<?php echo ((is_array($_tmp=$this->_tpl_vars['village']['name'])) ? $this->_run_mod_handler('urldecode', true, $_tmp) : urldecode($_tmp)); ?>
"><?php echo ((is_array($_tmp=$this->_tpl_vars['village']['name'])) ? $this->_run_mod_handler('urldecode', true, $_tmp) : urldecode($_tmp)); ?>
</option>
<?php endforeach; else: ?>
	<option value="">-- keine Dörfer vorhanden</option>
<?php endif; unset($_from); ?>
</select>
.
<br />
<table class="vis">
	<tr>
		<th>Cladiri</th>
		<th>Nivel*</th>
	</tr>
	<?php $_from = $this->_tpl_vars['needed']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['name'] => $this->_tpl_vars['dbname']):
?>
	<tr>
		<td><img src="../graphic/buildings/<?php echo $this->_tpl_vars['dbname']; ?>
.png"> <?php echo $this->_tpl_vars['name']; ?>
</td>
		<td><input name="<?php echo $this->_tpl_vars['dbname']; ?>
" id="<?php echo $this->_tpl_vars['dbname']; ?>
" type="text" size="5" value="na" style="text-align:center;border:1px solid #804000;background-color:#F8F4E8;" /></td>
	</tr>
	<?php endforeach; endif; unset($_from); ?>
	<tr>
		<td colspan="2">
		<input type="submit" value="Schimba" style="text-align:center;border:2px solid #804000;background-color:#F8F4E8;padding:3px;width:100%;" /> 
		</td>
	</tr>
</table>

<h4>* Notificare</h4>
<p><i>na</i> = Nici o schimbare</p>

<h4>Alte optiuni</h5>
<a href="javascript:set_maxstage()">&raquo; Totul la maxim</a><br />
<a href="javascript:set_all_na()">&raquo; Intoarce totul la <em>na</em></a>
</form>

<script type="text/javascript">
<!--

/**
 * JavaScript Functions generated by village_editor eXtension 
 */

<?php echo '
function set_maxstage() {
'; ?>


<?php $_from = $this->_tpl_vars['max_lvl']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['dname'] => $this->_tpl_vars['level']):
?>
	document.getElementById('<?php echo $this->_tpl_vars['dname']; ?>
').value = <?php echo $this->_tpl_vars['level']; ?>
;
<?php endforeach; endif; unset($_from); ?>

<?php echo '
}
'; ?>


<?php echo '
function set_all_na() {
'; ?>


<?php $_from = $this->_tpl_vars['max_lvl']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['dname'] => $this->_tpl_vars['level']):
?>
	document.getElementById('<?php echo $this->_tpl_vars['dname']; ?>
').value = "na";
<?php endforeach; endif; unset($_from); ?>

<?php echo '
}
'; ?>

//-->
</script>

<!--  
Debugger:
<?php echo $this->_tpl_vars['v_debug']; ?>

-->