<tr align="right">
                                                                                                                                        <td align="left" width ="33%"><a href="?article=units">&laquo; Descrierea unitatilor</a></td>
                                                                                                                                <td align="center" width ="33%"><a href="?article="></a></td>

                                                                                                                                        <td align="right" width ="33%"><a href="?article=fight">Sistemul de lupta &raquo;</a></td>
                                                                                                                        </tr>
                                                </table>

                                        </td>
                                </tr>
                                <tr>
                                        <td>
						<h1>Tabelul punctelor</h1>
						
<p>Puncte obtii pentru constructia de cladiri. În momentul în care o cladire este gata, îti vor fi adaugate punctele si ti se va recalcula pozitia în clasament (câteodata calculele acestea vor fi încete, pentru a usura functionarea serverului). Pentru cercetare sau unitati nu se acorda puncte.</p>

<p>Se vor arata diferentele de puncte între diferite niveluri.</p>
<p><a href="?article=points&total">Punctaj total</a></p>

<table class="vis">
<tr><th>nivelul</th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=main', 550, 520)"><img src="/graphic/buildings/main.png" alt="Cladirea principala" title="Cladirea principala"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=barracks', 550, 520)"><img src="/graphic/buildings/barracks.png" alt="Cazarma" title="Cazarma"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=stable', 550, 520)"><img src="/graphic/buildings/stable.png" alt="Grajd" title="Grajd"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=garage', 550, 520)"><img src="/graphic/buildings/garage.png" alt="Atelier" title="Atelier"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=snob', 550, 520)"><img src="/graphic/buildings/snob.png" alt="Curte nobila" title="Curte nobila"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=smith', 550, 520)"><img src="/graphic/buildings/smith.png" alt="Fierarie" title="Fierarie"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=place', 550, 520)"><img src="/graphic/buildings/place.png" alt="Piata centrala" title="Piata centrala"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=statue', 550, 520)"><img src="/graphic/buildings/statue.png" alt="Statuie" title="Statuie"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=market', 550, 520)"><img src="/graphic/buildings/market.png" alt="Târg" title="Târg"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=wood', 550, 520)"><img src="/graphic/buildings/wood.png" alt="Taietori de lemne" title="Taietori de lemne"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=stone', 550, 520)"><img src="/graphic/buildings/stone.png" alt="Mina de argila" title="Mina de argila"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=iron', 550, 520)"><img src="/graphic/buildings/iron.png" alt="Mina de fier" title="Mina de fier"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=farm', 550, 520)"><img src="/graphic/buildings/farm.png" alt="Ferma" title="Ferma"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=storage', 550, 520)"><img src="/graphic/buildings/storage.png" alt="Magazie" title="Magazie"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=hide', 550, 520)"><img src="/graphic/buildings/hide.png" alt="Ascunzatoare" title="Ascunzatoare"/></th>
	<th><a href="javascript:popup_scroll('http://localhost/popup_building.php?building=wall', 550, 520)"><img src="/graphic/buildings/wall.png" alt="Zid" title="Zid"/></th>
</tr>

<tr>
	<td>1</td>
		<td>10</td>
		<td>16</td>
		<td>20</td>
		<td>24</td>
		<td>512</td>
		<td>19</td>
		<td>0</td>
		<td>24</td>
		<td>10</td>
		<td>6</td>
		<td>6</td>
		<td>6</td>
		<td>5</td>
		<td>6</td>
		<td>5</td>
		<td>8</td>
	</tr>
<tr>
	<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td></td>
		<td>4</td>
		<td></td>
		<td></td>
		<td>2</td>
		<td>1</td>
		<td>1</td>
		<td>1</td>
		<td>1</td>
		<td>1</td>
		<td>1</td>
		<td>2</td>
	</tr>
<tr>
	<td>3</td>
		<td>2</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td></td>
		<td>4</td>
		<td></td>
		<td></td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>1</td>
		<td>2</td>
		<td>1</td>
		<td>2</td>
	</tr>
<tr>
	<td>4</td>
		<td>3</td>
		<td>5</td>
		<td>6</td>
		<td>6</td>
		<td></td>
		<td>6</td>
		<td></td>
		<td></td>
		<td>3</td>
		<td>1</td>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
	</tr>
<tr>
	<td>5</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>9</td>
		<td></td>
		<td>6</td>
		<td></td>
		<td></td>
		<td>4</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>1</td>
		<td>2</td>
		<td>1</td>
		<td>3</td>
	</tr>
<tr>
	<td>6</td>
		<td>4</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td></td>
		<td>8</td>
		<td></td>
		<td></td>
		<td>4</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>2</td>
		<td>3</td>
		<td>2</td>
		<td>3</td>
	</tr>
<tr>
	<td>7</td>
		<td>5</td>
		<td>8</td>
		<td>10</td>
		<td>12</td>
		<td></td>
		<td>10</td>
		<td></td>
		<td></td>
		<td>5</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
	</tr>
<tr>
	<td>8</td>
		<td>6</td>
		<td>9</td>
		<td>12</td>
		<td>14</td>
		<td></td>
		<td>11</td>
		<td></td>
		<td></td>
		<td>6</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>3</td>
		<td>5</td>
	</tr>
<tr>
	<td>9</td>
		<td>7</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td></td>
		<td>14</td>
		<td></td>
		<td></td>
		<td>7</td>
		<td>5</td>
		<td>5</td>
		<td>5</td>
		<td>3</td>
		<td>5</td>
		<td>3</td>
		<td>5</td>
	</tr>
<tr>
	<td>10</td>
		<td>9</td>
		<td>14</td>
		<td>17</td>
		<td>21</td>
		<td></td>
		<td>16</td>
		<td></td>
		<td></td>
		<td>9</td>
		<td>5</td>
		<td>5</td>
		<td>5</td>
		<td>5</td>
		<td>5</td>
		<td>5</td>
		<td>7</td>
	</tr>
<tr>
	<td>11</td>
		<td>10</td>
		<td>16</td>
		<td>21</td>
		<td>25</td>
		<td></td>
		<td>20</td>
		<td></td>
		<td></td>
		<td>10</td>
		<td>6</td>
		<td>6</td>
		<td>6</td>
		<td>5</td>
		<td>6</td>
		<td></td>
		<td>9</td>
	</tr>
<tr>
	<td>12</td>
		<td>12</td>
		<td>20</td>
		<td>25</td>
		<td>29</td>
		<td></td>
		<td>23</td>
		<td></td>
		<td></td>
		<td>12</td>
		<td>8</td>
		<td>8</td>
		<td>8</td>
		<td>6</td>
		<td>8</td>
		<td></td>
		<td>9</td>
	</tr>
<tr>
	<td>13</td>
		<td>15</td>
		<td>24</td>
		<td>29</td>
		<td>36</td>
		<td></td>
		<td>28</td>
		<td></td>
		<td></td>
		<td>15</td>
		<td>8</td>
		<td>8</td>
		<td>8</td>
		<td>8</td>
		<td>8</td>
		<td></td>
		<td>12</td>
	</tr>
<tr>
	<td>14</td>
		<td>18</td>
		<td>28</td>
		<td>36</td>
		<td>43</td>
		<td></td>
		<td>34</td>
		<td></td>
		<td></td>
		<td>18</td>
		<td>11</td>
		<td>11</td>
		<td>11</td>
		<td>8</td>
		<td>11</td>
		<td></td>
		<td>15</td>
	</tr>
<tr>
	<td>15</td>
		<td>21</td>
		<td>34</td>
		<td>43</td>
		<td>51</td>
		<td></td>
		<td>41</td>
		<td></td>
		<td></td>
		<td>21</td>
		<td>13</td>
		<td>13</td>
		<td>13</td>
		<td>11</td>
		<td>13</td>
		<td></td>
		<td>17</td>
	</tr>
<tr>
	<td>16</td>
		<td>26</td>
		<td>42</td>
		<td>51</td>
		<td></td>
		<td></td>
		<td>49</td>
		<td></td>
		<td></td>
		<td>26</td>
		<td>15</td>
		<td>15</td>
		<td>15</td>
		<td>13</td>
		<td>15</td>
		<td></td>
		<td>20</td>
	</tr>
<tr>
	<td>17</td>
		<td>31</td>
		<td>49</td>
		<td>62</td>
		<td></td>
		<td></td>
		<td>58</td>
		<td></td>
		<td></td>
		<td>31</td>
		<td>19</td>
		<td>19</td>
		<td>19</td>
		<td>15</td>
		<td>19</td>
		<td></td>
		<td>25</td>
	</tr>
<tr>
	<td>18</td>
		<td>37</td>
		<td>59</td>
		<td>74</td>
		<td></td>
		<td></td>
		<td>71</td>
		<td></td>
		<td></td>
		<td>37</td>
		<td>22</td>
		<td>22</td>
		<td>22</td>
		<td>19</td>
		<td>22</td>
		<td></td>
		<td>29</td>
	</tr>
<tr>
	<td>19</td>
		<td>44</td>
		<td>71</td>
		<td>88</td>
		<td></td>
		<td></td>
		<td>84</td>
		<td></td>
		<td></td>
		<td>44</td>
		<td>27</td>
		<td>27</td>
		<td>27</td>
		<td>22</td>
		<td>27</td>
		<td></td>
		<td>36</td>
	</tr>
<tr>
	<td>20</td>
		<td>53</td>
		<td>85</td>
		<td>107</td>
		<td></td>
		<td></td>
		<td>101</td>
		<td></td>
		<td></td>
		<td>53</td>
		<td>32</td>
		<td>32</td>
		<td>32</td>
		<td>27</td>
		<td>32</td>
		<td></td>
		<td>43</td>
	</tr>
<tr>
	<td>21</td>
		<td>64</td>
		<td>102</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>64</td>
		<td>38</td>
		<td>38</td>
		<td>38</td>
		<td>32</td>
		<td>38</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>22</td>
		<td>77</td>
		<td>123</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>77</td>
		<td>46</td>
		<td>46</td>
		<td>46</td>
		<td>38</td>
		<td>46</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>23</td>
		<td>92</td>
		<td>147</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>92</td>
		<td>55</td>
		<td>55</td>
		<td>55</td>
		<td>46</td>
		<td>55</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>24</td>
		<td>110</td>
		<td>177</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>110</td>
		<td>66</td>
		<td>66</td>
		<td>66</td>
		<td>55</td>
		<td>66</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>25</td>
		<td>133</td>
		<td>212</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>133</td>
		<td>80</td>
		<td>80</td>
		<td>80</td>
		<td>66</td>
		<td>80</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>26</td>
		<td>159</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>95</td>
		<td>95</td>
		<td>95</td>
		<td>80</td>
		<td>95</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>27</td>
		<td>191</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>115</td>
		<td>115</td>
		<td>115</td>
		<td>95</td>
		<td>115</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>28</td>
		<td>229</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>137</td>
		<td>137</td>
		<td>137</td>
		<td>115</td>
		<td>137</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>29</td>
		<td>274</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>165</td>
		<td>165</td>
		<td>165</td>
		<td>137</td>
		<td>165</td>
		<td></td>
		<td></td>
	</tr>
<tr>
	<td>30</td>
		<td>330</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>198</td>
		<td>198</td>
		<td>198</td>
		<td>165</td>
		<td>198</td>
		<td></td>
		<td></td>
	</tr>
</table>                                   </td>
                                </tr>
                                <tr>
                                        <td>


                                        <table class="vis" width="100%">
                                                <tr align="right">
                                                                                                                        <td align="left" width ="33%"><a href="?article=units">&laquo; Descrierea unitatilor</a></td>
                                                                                                                        <td align="center" width ="33%"><a href="?article="></a></td>
                                                                                                                        <td align="right" width ="33%"><a href="?article=fight">Sistemul de lupta &raquo;</a></td>
                                                                                                        </tr>